### ISSUE TITLE
The requested URL returned error: 404 Not Found

### ISSUE THREAD

**Issue by berejznoy** [yktoo/commento-docker-compose#2]
Добрый день. 
На 4м шаге при выполнении docker-compose -p commento build возникает ошибка: 
The requested URL returned error: 404 Not Found
ERROR: Service 'certbot' failed to build: The command '/bin/sh -c apk add --no-cache curl &&     mkdir -p /conf &&     curl -fsSL https://raw.githubusercontent.com/certbot/certbot/master/certbot-nginx/certbot_nginx/options-ssl-nginx.conf > "/conf/options-ssl-nginx.conf" &&     curl -fsSL https://raw.githubusercontent.com/certbot/certbot/master/certbot/ssl-dhparams.pem > "/conf/ssl-dhparams.pem" &&     openssl req -x509 -nodes -newkey rsa:1024 -days 1 -keyout '/conf/privkey.pem' -out '/conf/fullchain.pem' -subj '/CN=localhost' &&     apk del curl' returned a non-zero code: 22

**Comment by ahayman** [comment]
Same here:

> curl: (22) The requested URL returned error: 404 Not Found
ERROR: Service 'certbot' failed to build: The command '/bin/sh -c apk add --no-cache curl &&     mkdir -p /conf &&     curl -fsSL https://raw.githubusercontent.com/certbot/certbot/master/certbot-nginx/certbot_nginx/options-ssl-nginx.conf > "/conf/options-ssl-nginx.conf" &&     curl -fsSL https://raw.githubusercontent.com/certbot/certbot/master/certbot/ssl-dhparams.pem > "/conf/ssl-dhparams.pem" &&     openssl req -x509 -nodes -newkey rsa:1024 -days 1 -keyout '/conf/privkey.pem' -out '/conf/fullchain.pem' -subj '/CN=localhost' &&     apk del curl' returned a non-zero code: 22

Seems to be these URLs are failing: https://raw.githubusercontent.com/certbot/certbot/master/certbot/ssl-dhparams.pem
https://raw.githubusercontent.com/certbot/certbot/master/certbot-nginx/certbot_nginx/options-ssl-nginx.conf

It appears the URLs have changed to:
https://raw.githubusercontent.com/certbot/certbot/master/certbot/certbot/ssl-dhparams.pem
https://raw.githubusercontent.com/certbot/certbot/master/certbot-nginx/certbot_nginx/_internal/tls_configs/options-ssl-nginx.conf

**Comment by ahayman** [comment]
Looks like there's already a PR: https://github.com/yktoo/commento-docker-compose/pull/3

Just need to accept it :)

**Comment by berejznoy** [comment]
@ahayman Thank you

**Comment by yktoo** [comment]
Closed via #3.
