### ISSUE TITLE
commento.service failed

### ISSUE THREAD

**Issue by aleh-zubaryk** [yktoo/commento-docker-compose#5]
Прошёл все шаги установки, вписал переменные в файл yml, создал симлинки, запустил сервис.
При проверке статуса выдаёт Active:failed ... status=1/FAILURE.
Что может быть не так?
![Скриншот](https://user-images.githubusercontent.com/11088044/83510713-217cb900-a4d6-11ea-96c9-efedb302c76d.JPG)

**Comment by yktoo** [comment]
> Host is already in use in another container

Нужно удалить все контейнеры. Сначала всё остановить, потом `docker container prune`, потом запустить заново.

**Comment by aleh-zubaryk** [comment]
Остановил, удалил, запустил заново. Аналогичная ошибка.
Вопрос @yktoo: то, что у меня пока в переменных окружения в качестве имени сайта не имя, а IP-адрес, может влиять на ситуацию?

**Comment by yktoo** [comment]
Я не знаю, нужно смотреть логи. IP практически наверняка не пройдёт, так как SSL-сертификат выдаётся на имя. Я советую запустить всё вручную, предварительно остановив systemd-сервис:

```bash
systemctl stop commento.service
cd /opt/commento
docker-compose -p commento up
```

В выводе в консоли будет лучше видно, что не так.

**Comment by aleh-zubaryk** [comment]
Судя по всему, nginx ругается на занятость порта для прослушивания. 
Вопрос @yktoo: у меня на этом CentOS-сервере развернут другой веб-сервер, на котором крутится сайт, вне докера. Это может быть причиной? Я думал, что т.к. докер – выделенная среда, конфликтов с существующим веб-сервером не будет.
![attach](https://user-images.githubusercontent.com/11088044/84270146-e829f600-ab32-11ea-9f5c-46a1940470b8.JPG)

**Comment by yktoo** [comment]
Порты 80 и 443 проброшены на хост, иначе этим сервером будет невозможно пользоваться. Их можно поменять в `docker-compose.yml` на другие значения (например, на 8080 и 8443). И Docker тут ни при чём, физически невозможно запустить два сервера на одной машине на одном порту.

**Comment by aleh-zubaryk** [comment]
Ещё вопрос, теперь по PostgreSQL в докере. Ковырял сам, но так результата и не добился. После разворачивания в докере и запуска службы commento Postgre должен прослушивать порт 5432 и по нему commento должен подключиться к БД.
В моём же случае якобы порт прослушивается, но при подключении пишет "connection refused". Причём если проверять прослушиваемые порты через netstat, то они слушаются только по протоколу Ipv6, ровно как и порты для nginx.
Пробовал вручную прописывать порты в docker-compose.yml, менять порты в конф. файле внутри image для postgre, переустанавливать всё по нескольку раз.
Насколько понимаю, причина в том, что postgre не слушает 127.0.0.1:5432. Хотя в конф. файлах я вижу обратное. Куда копать, @yktoo ?
![Снимок](https://user-images.githubusercontent.com/11088044/84890084-976e4c00-b0a2-11ea-8f37-005f9973854e.JPG)

**Comment by yktoo** [comment]
В оригинальном `docker-compose.yml` порты PostgreSQL на хост вообще не пробрасываются, так как незачем. Сервер PostgreSQL доступен исключительно внутри сети Docker под названием `commento_network`.

При желании можно добавить mapping:

```yaml
    postgres:
        image: postgres:11
        ports:
          - 5432:5432
        ...
```
Это откроет его для доступа извне (так что нужно учитывать все сопутствующие этому риски).

P.S. Я бы очень советовал использовать для инспекции контейнеров, портов и т.д. `docker ps` и `docker inspect` вместо `netstat`.

**Comment by aleh-zubaryk** [comment]
Ещё вопрос по связке nginx+certbot. Если я использую не стандартные порты 80 и 443, а другие для подключения к commento, кроме как в docker-compose.yml мне нужно их где-то ещё менять? Например, в /nginx/commento.conf или ещё где-то? У меня сейчас не стартует nginx, потому что не видит файлов с ключами для хоста. А они там не появляются, видимо, потому что certbot не может их там создать. Права на папку все есть, поэтому делаю вывод, что он просто не получает доступ к сайту для валидации. Или проблема может быть в чём-то другом, @yktoo ?
![Снимок](https://user-images.githubusercontent.com/11088044/85234897-82cee280-b419-11ea-8b3c-c96142076f6d.JPG)

**Comment by yktoo** [comment]
`certbot` ожидает `nginx` на [порту 80](https://github.com/yktoo/commento-docker-compose/blob/master/certbot/bootstrap.sh#L9), это нужно изменить. Также [в docker-compose](https://github.com/yktoo/commento-docker-compose/blob/master/docker-compose.yml#L72) и в [commento.conf](https://github.com/yktoo/commento-docker-compose/blob/master/nginx/commento.conf#L24) — достаточно поискать по строке `80` (или `443`).

**Comment by aleh-zubaryk** [comment]
Поменял везде порты 80 и 443 на 9012 и 9013 соответственно, в [docker-compose](https://github.com/yktoo/commento-docker-compose/blob/master/docker-compose.yml#L72) пробовал и 9012:9012, и 9012:80, результат одинаковый. Пробовал делать выключение-включение контейнеров, удалять все и заново ставить, не помогло. 
Сертификат не хочет выписываться, и nginx завершает работу из-за его отсутствия.
![Снимок](https://user-images.githubusercontent.com/11088044/85797184-cd1ad100-b743-11ea-8576-ed2befe58dc0.JPG)
Куда можно копнуть, @yktoo ?

**Comment by yktoo** [comment]
Согласно [этому треду](https://community.letsencrypt.org/t/using-encrypt-for-non-standard-ports/20164), сертификат обязан выдаваться на стандартные порты 80/443, либо нужно настраивать DNS-запись `dns-01`.

Всё это уже становится чересчур сложно для дискуссии в этом месте, так что советую вам либо вернуться к стандартной конфигурации, поддерживаемой данным проектом, либо нанять соответствующего специалиста.

**Comment by aleh-zubaryk** [comment]
Спасибо за наводку, попробую. Сам понимаю, поэтому уже дальше чуть что вернусь к стандартной конфигурации
